title = "The Programmer Polemic"
subtitle = "A casual history and analysis of a professional culture" 
author = "Nico OR"
content_path = "assets/polemical/polemical.md"
link = "articles/polemical.html"
date = "2026-06-18"
hidden = true
